INSERT INTO DEMO_USER(USER_CODE,PCODE,USER_ROLE)
  SELECT 'admin', '$2a$10$VGciz8IkKHS4LHeDItXAKOtZv1wSQYLel5ebHK4B8xLvcmzqF8XrG', 'ROLE_ADMIN'
  WHERE
  NOT EXISTS (
    SELECT USER_CODE FROM DEMO_USER WHERE USER_CODE = 'admin'
  );